/* Side-effect free so tests can enumerate it: a write with no `endedOk` reason
   must refuse an ended board, and an unclassified route reddens the suite. */

export const ROUTES = [
  { method: 'GET', pattern: /^\/health$/, handler: 'health', write: false },
  { method: 'GET', pattern: /^\/assets\/([\w.-]+)$/, handler: 'asset', write: false },
  { method: 'GET', pattern: /^\/$/, handler: 'index', write: false },
  { method: 'GET', pattern: /^\/b\/([^/]+)$/, handler: 'boardPage', write: false },
  { method: 'GET', pattern: /^\/events$/, handler: 'sseGlobal', write: false },
  { method: 'GET', pattern: /^\/b\/([^/]+)\/events$/, handler: 'sse', write: false },
  { method: 'GET', pattern: /^\/api\/b\/([^/]+)\/state$/, handler: 'state', write: false },

  {
    method: 'POST',
    pattern: /^\/api\/open$/,
    handler: 'open',
    write: true,
    endedOk: 'creates a board; the path carries no key that could be ended',
  },
  { method: 'POST', pattern: /^\/api\/b\/([^/]+)\/publish$/, handler: 'publish', write: true },
  { method: 'POST', pattern: /^\/api\/b\/([^/]+)\/await$/, handler: 'await', write: true },
  {
    method: 'POST',
    pattern: /^\/api\/b\/([^/]+)\/ack$/,
    handler: 'ack',
    write: true,
    endedOk: 'agent cursor bookkeeping; an agent must still be able to drain an ended board',
  },
  { method: 'GET', pattern: /^\/api\/b\/([^/]+)\/feedback$/, handler: 'feedbackReplay', write: false },
  { method: 'POST', pattern: /^\/api\/b\/([^/]+)\/feedback$/, handler: 'feedbackCreate', write: true },
  {
    method: 'DELETE',
    pattern: /^\/api\/b\/([^/]+)\/feedback\/(\d+)$/,
    handler: 'feedbackDelete',
    write: true,
    endedOk: 'discards a draft that can no longer be sent; clearing leftovers is not reaching the agent',
  },
  { method: 'POST', pattern: /^\/api\/b\/([^/]+)\/send$/, handler: 'send', write: true },
  { method: 'POST', pattern: /^\/api\/b\/([^/]+)\/widget$/, handler: 'widget', write: true },
  { method: 'POST', pattern: /^\/api\/b\/([^/]+)\/chat$/, handler: 'chat', write: true },
  {
    method: 'POST',
    pattern: /^\/api\/b\/([^/]+)\/reply$/,
    handler: 'reply',
    write: true,
    endedOk: 'the agent answering; the end stops what the reviewer sends in, not the agent closing out',
  },
  {
    method: 'POST',
    pattern: /^\/api\/b\/([^/]+)\/cancel-waiting$/,
    handler: 'cancelWaiting',
    write: true,
    endedOk: 'releases waiters, which ending does anyway',
  },
  { method: 'GET', pattern: /^\/api\/status$/, handler: 'statusAll', write: false },
  { method: 'GET', pattern: /^\/api\/config$/, handler: 'config', write: false },
  {
    method: 'POST',
    pattern: /^\/api\/config$/,
    handler: 'config',
    write: true,
    endedOk: 'daemon-wide setting, not tied to any board',
  },
  { method: 'GET', pattern: /^\/api\/b\/([^/]+)\/status$/, handler: 'statusOne', write: false },
  {
    method: 'POST',
    pattern: /^\/api\/b\/([^/]+)\/end$/,
    handler: 'end',
    write: true,
    endedOk: 'reopen is the only way back from ended',
  },
  { method: 'POST', pattern: /^\/api\/gc$/, handler: 'gc', write: true, endedOk: 'housekeeping across all boards' },
  { method: 'POST', pattern: /^\/api\/purge$/, handler: 'purge', write: true, endedOk: 'housekeeping across all boards' },

  { method: 'GET', pattern: /^\/whiteboard-frame$/, handler: 'whiteboardFrame', write: false },
  { method: 'GET', pattern: /^\/island-frame$/, handler: 'islandFrame', write: false },
  { method: 'GET', pattern: /^\/whiteboard-assets\/(.+)$/, handler: 'whiteboardAsset', write: false },
  {
    method: 'POST',
    pattern: /^\/api\/b\/([^/]+)\/whiteboard-channel$/,
    handler: 'whiteboardChannel',
    write: true,
    endedOk: 'authenticates a read-only view of an already-saved drawing; reads stay legal',
  },
  { method: 'GET', pattern: /^\/api\/b\/([^/]+)\/whiteboard\/(\d+)$/, handler: 'whiteboardGet', write: false },
  { method: 'PUT', pattern: /^\/api\/b\/([^/]+)\/whiteboard\/(\d+)$/, handler: 'whiteboardPut', write: true },
  {
    method: 'POST',
    pattern: /^\/api\/b\/([^/]+)\/whiteboard\/(\d+)\/feedback$/,
    handler: 'whiteboardFeedback',
    write: true,
  },
]
