#!/usr/bin/env bash
# Install (or re-install) the easel daemon as a launchd user agent and put the
# easel CLI on PATH. Idempotent: re-running converges to the same state.
set -euo pipefail

LABEL="com.sentience.easeld"
PORT="${EASEL_PORT:-4400}"
STATE_DIR="${EASEL_DATA_DIR:-$HOME/.easel}"
PLIST_DIR="$HOME/Library/LaunchAgents"
PLIST="$PLIST_DIR/$LABEL.plist"

# Repo root is derived from this script's own location — never hardcoded, so a
# clone anywhere installs correctly.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE="$ROOT/install/$LABEL.plist.template"
CLI="$ROOT/cli/easel.js"

say() { printf '  %s\n' "$*"; }

xml_escape() {
  printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

# For values that reach the plist through sed: XML text first, then sed's
# replacement side. Anything inserted by other means wants xml_escape alone.
subst_value() {
  xml_escape "$1" | sed -e 's/[\\&|]/\\&/g'
}

# A launchd agent does not inherit the installing shell, so the override the
# launcher looks for only reaches it if the plist carries it.
node_env_xml() {
  [ -n "${EASEL_NODE:-}" ] || return 0
  # xml_escape, not subst_value: this goes in through awk, not sed.
  printf '    <key>EASEL_NODE</key>\n    <string>%s</string>' "$(xml_escape "$EASEL_NODE")"
}

usage() {
  cat <<EOF
usage: install.sh [--uninstall] [--bin-dir DIR]

  --uninstall   bootout the agent, remove the plist and the CLI symlink
  --bin-dir     where to symlink the CLI (default: first writable of
                /usr/local/bin, \$HOME/.local/bin)
EOF
}

BIN_DIR=""
UNINSTALL=0
while [ $# -gt 0 ]; do
  case "$1" in
    --uninstall) UNINSTALL=1; shift ;;
    --bin-dir) BIN_DIR="${2:?--bin-dir needs a path}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

# Not /opt/homebrew/bin: easel is not distributed through homebrew, and writing
# into brew's prefix makes an unrelated package manager look like the owner.
pick_bin_dir() {
  if [ -n "$BIN_DIR" ]; then printf '%s\n' "$BIN_DIR"; return; fi
  for d in /usr/local/bin "$HOME/.local/bin"; do
    if [ -d "$d" ] && [ -w "$d" ]; then printf '%s\n' "$d"; return; fi
  done
  printf '%s\n' "$HOME/.local/bin"
}

# Teardown is asynchronous: bootstrapping while the old service is still
# terminating fails with "Bootstrap failed: 5: Input/output error".
bootout_if_loaded() {
  launchctl bootout "gui/$UID/$LABEL" 2>/dev/null || true
  local _
  for _ in $(seq 1 60); do
    launchctl print "gui/$UID/$LABEL" >/dev/null 2>&1 || return 0
    sleep 0.25
  done
  echo "warning: $LABEL still present 15s after bootout" >&2
  return 0
}

# The installed `easel` is a generated shim, not a symlink: it has to carry
# the port this install chose, which the CLI otherwise cannot know.
MARKER="# generated by easel install.sh — root:"

# Also claims the pre-shim form: a bare symlink to this checkout's CLI, which
# earlier installs left behind. Upgrading one must not need manual cleanup.
owns_entry() {
  local path="$1"
  if [ -L "$path" ]; then
    [ "$(readlink "$path")" = "$CLI" ]
    return
  fi
  [ -f "$path" ] || return 1
  grep -qxF "$MARKER $ROOT" "$path" 2>/dev/null
}

write_entry() {
  local path="$1"
  # rm first: writing through a surviving symlink would clobber its target.
  rm -f "$path"
  printf '%s\n' \
    '#!/bin/sh' \
    "$MARKER $ROOT" \
    "export EASEL_URL=\"\${EASEL_URL:-http://127.0.0.1:$PORT}\"" \
    "exec node \"$CLI\" \"\$@\"" > "$path"
  chmod +x "$path"
}

# Every dir an install may have written to, now or in the past. Homebrew is no
# longer a target, but dropping it here would orphan shims earlier versions left.
SWEEP_DIRS=(/opt/homebrew/bin /usr/local/bin "$HOME/.local/bin")

# Removing a shim from a dir we no longer pick IS the relocation — the
# replacement is already written. Unmarked entries belong to someone else.
relocate_stale_entries() {
  local dir name link
  for dir in "${SWEEP_DIRS[@]}"; do
    [ "$dir" = "$DEST_DIR" ] && continue
    for name in easel queue-lint; do
      link="$dir/$name"
      [ -f "$link" ] || continue
      grep -qF "$MARKER" "$link" 2>/dev/null || continue
      rm -f "$link"
      say "relocated $link -> $DEST_DIR/$name"
    done
  done
}

# An unrelated entry on PATH belongs to someone else, on install and uninstall alike.
remove_owned_link() {
  local link="$1/$2"
  [ -e "$link" ] || [ -L "$link" ] || return 0
  if owns_entry "$link"; then
    rm -f "$link"; say "removed $link"
  else
    say "left $link alone — not installed by this checkout"
  fi
}

if [ "$UNINSTALL" -eq 1 ]; then
  echo "easel: uninstalling"
  bootout_if_loaded
  say "agent booted out"
  if [ -f "$PLIST" ]; then rm -f "$PLIST"; say "removed $PLIST"; else say "no plist at $PLIST"; fi
  LINK_DIRS=("${SWEEP_DIRS[@]}")
  [ -n "$BIN_DIR" ] && LINK_DIRS+=("$BIN_DIR")
  for d in "${LINK_DIRS[@]}"; do
    remove_owned_link "$d" easel
    remove_owned_link "$d" queue-lint
  done
  echo "easel: uninstalled"
  exit 0
fi

echo "easel: installing from $ROOT"

LAUNCHER="$ROOT/install/easeld-launcher.sh"
[ -f "$LAUNCHER" ] || { echo "error: missing $LAUNCHER" >&2; exit 1; }
chmod +x "$LAUNCHER"
# Install-time sanity only — the plist points at the launcher, which re-resolves
# node on every launch, so this path is never baked in.
NODE_BIN="$(command -v node || true)"
[ -n "$NODE_BIN" ] || { echo "error: node not found on PATH" >&2; exit 1; }
say "node (install-time check only): $NODE_BIN ($(node --version))"
say "launcher: $LAUNCHER resolves node at each launch"

[ -f "$TEMPLATE" ] || { echo "error: missing $TEMPLATE" >&2; exit 1; }

mkdir -p "$STATE_DIR" "$PLIST_DIR"
say "state dir: $STATE_DIR"

if [ ! -f "$CLI" ]; then
  echo "error: CLI entrypoint not found at $CLI" >&2
  exit 1
fi
chmod +x "$CLI"

DEST_DIR="$(pick_bin_dir)"
mkdir -p "$DEST_DIR"
ENTRY="$DEST_DIR/easel"
if { [ -e "$ENTRY" ] || [ -L "$ENTRY" ]; } && ! owns_entry "$ENTRY"; then
  echo "error: $ENTRY exists and was not installed by this checkout" >&2
  echo "  remove it yourself, or pick another directory with --bin-dir" >&2
  exit 1
fi
write_entry "$ENTRY"
say "cli: $ENTRY -> $CLI (port $PORT)"

# queue-lint rides the same converge path, so `easel update` keeps it current.
LINT="$ROOT/cli/queue-lint.sh"
chmod +x "$LINT"
LINT_ENTRY="$DEST_DIR/queue-lint"
if { [ -e "$LINT_ENTRY" ] || [ -L "$LINT_ENTRY" ]; } && ! owns_entry "$LINT_ENTRY"; then
  echo "error: $LINT_ENTRY exists and was not installed by this checkout" >&2
  echo "  remove it yourself, or pick another directory with --bin-dir" >&2
  exit 1
fi
rm -f "$LINT_ENTRY"
printf '%s\n' \
  '#!/bin/sh' \
  "$MARKER $ROOT" \
  "exec bash \"$LINT\" \"\$@\"" > "$LINT_ENTRY"
chmod +x "$LINT_ENTRY"
say "cli: $LINT_ENTRY -> $LINT"

relocate_stale_entries

NODE_ENV_XML="$(node_env_xml)"
[ -z "$NODE_ENV_XML" ] || say "pinning EASEL_NODE=$EASEL_NODE into the agent"

TMP_PLIST="$(mktemp)"
trap 'rm -f "$TMP_PLIST"' EXIT
sed -e "s|__LABEL__|$(subst_value "$LABEL")|g" \
    -e "s|__ROOT__|$(subst_value "$ROOT")|g" \
    -e "s|__PORT__|$(subst_value "$PORT")|g" \
    -e "s|__STATE__|$(subst_value "$STATE_DIR")|g" \
    -e "s|__PATH__|$(subst_value "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin")|g" \
    "$TEMPLATE" \
  | NODE_ENV_XML="$NODE_ENV_XML" awk \
      'BEGIN { repl = ENVIRON["NODE_ENV_XML"] }
       /^__NODE_ENV__$/ { if (repl != "") print repl; next } { print }' \
  > "$TMP_PLIST"

if [ -f "$PLIST" ] && cmp -s "$TMP_PLIST" "$PLIST"; then
  say "plist unchanged"
else
  cp "$TMP_PLIST" "$PLIST"
  say "wrote $PLIST"
fi

# Always bootout before bootstrap: bootstrap on an already-loaded label fails
# with EALREADY, so this is what makes a re-run converge instead of erroring.
bootout_if_loaded
launchctl bootstrap "gui/$UID" "$PLIST"
launchctl enable "gui/$UID/$LABEL" 2>/dev/null || true
say "agent bootstrapped: $LABEL"

printf '  waiting for daemon on port %s' "$PORT"
ok=0
for _ in $(seq 1 40); do
  if curl -fsS -m 1 "http://127.0.0.1:$PORT/health" >/dev/null 2>&1; then ok=1; break; fi
  printf '.'
  sleep 0.25
done
printf '\n'

if [ "$ok" -eq 1 ]; then
  say "daemon healthy: http://127.0.0.1:$PORT/health"
else
  say "daemon did not answer /health within 10s — see $STATE_DIR/daemon.log"
  exit 1
fi

echo "easel: installed"
